### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by Joththeboop** [JamCoreModding/UtilityBelt#14] opened 2022-10-15 14:26 UTC
Havent encountered this type of crash before, have no idea what caused it or how to replicate it. The game just froze, kicked me from singleplayer, froze again and crashed
[crash.txt](https://github.com/JamCoreModding/UtilityBelt/files/9792297/crash.txt)

**Comment by Jamalam360** [comment] 2022-10-16 10:00
I'm going to say this is a duplicate of #13 I think, thank you for reporting though

**Closed** 2022-10-16 10:00 UTC
Labels: bug, duplicate, priority: high
